src/Entity/Show.php
<?php

namespace App\Entity;

use App\Repository\ShowRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ShowRepository::class)]
#[ORM\Table(name: '`show`')]
class Show
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $Numshow = null;

    #[ORM\Column]
    private ?int $Nbrseat = 30;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $Dateshow = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumshow(): ?int
    {
        return $this->Numshow;
    }

    public function setNumshow(int $Numshow): static
    {
        $this->Numshow = $Numshow;

        return $this;
    }

    public function getNbrseat(): ?int
    {
        return $this->Nbrseat;
    }

    public function setNbrseat(int $Nbrseat): static
    {
        $this->Nbrseat = $Nbrseat;

        return $this;
    }

    public function getDateshow(): ?\DateTimeInterface
    {
        return $this->Dateshow;
    }

    public function setDateshow(\DateTimeInterface $Dateshow): static
    {
        $this->Dateshow = $Dateshow;

        return $this;
    }
}

src/Entity/TheatrePlay.php
<?php

namespace App\Entity;

use App\Repository\TheatrePlayRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TheatrePlayRepository::class)]
class TheatrePlay
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Title = null;

    #[ORM\Column(length: 255)]
    private ?string $Genre = null;

    #[ORM\Column(length: 255)]
    private ?string $Duration = null;

    #[ORM\ManyToOne(inversedBy: 'theatrePlays')]
    private ?Show $Shows = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): static
    {
        $this->Title = $Title;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->Genre;
    }

    public function setGenre(string $Genre): static
    {
        $this->Genre = $Genre;

        return $this;
    }

    public function getDuration(): ?string
    {
        return $this->Duration;
    }

    public function setDuration(string $Duration): static
    {
        $this->Duration = $Duration;

        return $this;
    }

    public function getShows(): ?Show
    {
        return $this->Shows;
    }

    public function setShows(?Show $Shows): static
    {
        $this->Shows = $Shows;

        return $this;
    }
}

src/Form/TheatrType.php
<?php

namespace App\Form;

use App\Entity\Show;
use App\Entity\TheatrePlay;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
class TheatrType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Title')
            ->add('Genre')
            ->add('Duration')
            ->add('Shows', EntityType::class, [
                'class' => Show::class,
                'choice_label' => 'id',
            ])
            ->add('save', SubmitType::class, ['label' => 'Enregistrer'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => TheatrePlay::class,
        ]);
    }
}

src/Controller/TheatreController.php
<?php

namespace App\Controller;

use Doctrine\ORM\EntityManagerInterface;
use App\Entity\TheatrePlay;
use App\Form\TheatrType;
use App\Repository\TheatrePlayRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;

class TheatreController extends AbstractController
{
    #[Route('/displayplay', name: 'app_displayplay')]
    public function DisplayPlay(TheatrePlayRepository $tr): Response
    {
        $list = $tr->findAll();
        return $this->render(
            'theatre/list.html.twig',
            [
                "list" => $list
            ]
        );
    }
    #[Route('/displayAdd', name: 'Add_Show')]
    public function DisplayAdd(ManagerRegistry $doctrine, Request $request): Response
    {
        $tr = new TheatrePlay();
        $form = $this->createForm(TheatrType::class, $tr);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em = $doctrine->getManager(); // appel entity manager
            $em->persist($tr); // insert into
            $em->flush(); // d'envoyer tout ce qui a été persisté avant à la base de données
            return $this->redirectToRoute('app_displayplay');
        }
        return $this->render('theatre/add.html.twig', [
            'form' => $form->createView()
        ]);
    }
    #[Route('/Update/{id}', name: 'th_update')]
    public function update(ManagerRegistry $doctrine, Request $request, $id, TheatrePlayRepository $tr): response
    {
        $theatre = $tr->find($id);
        $form = $this->createForm(TheatrType::class, $theatre); // creation formulaire à partir de classe authortype
        $form->handleRequest($request); //traiter les données recus 
        if ($form->isSubmitted()) //verifier  form envoyer valide 
        {
            $em = $doctrine->getManager(); // appel entity manager
            $em->flush(); // d'envoyer tout ce qui a été persisté avant à la base de données
            return $this->redirectToRoute('app_displayplay');
        }
        return $this->render('theatre/update.html.twig', ['form' => $form->createView()]);
    }
    #[route('/delete/{id}', name: 'app_delete')]
    public function delete(TheatrePlayRepository $tr, int $id, EntityManagerInterface $entityManager): Response
    {
        $trr = $tr->find($id);
        $entityManager->remove($trr);
        $entityManager->flush();
        return $this->redirectToRoute('app_displayplay');
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text><text y=%221.3em%22 x=%220.2em%22 font-size=%2276%22 fill=%22%23fff%22>sf</text></svg>">
        {% block stylesheets %}
        {% endblock %}

        {% block javascripts %}
            {% block importmap %}{{ importmap('app') }}{% endblock %}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/theatre/Add.html.twig
{{form(form)}}

templates/theatre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello TheatreController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code>C:/Users/houss/OneDrive/Bureau/symfony/revEx1/src/Controller/TheatreController.php</code></li>
        <li>Your template at <code>C:/Users/houss/OneDrive/Bureau/symfony/revEx1/templates/theatre/index.html.twig</code></li>
    </ul>
</div>
{% endblock %}

templates/theatre/list.html.twig
<table border="1">
	<tr>
		<th>id</th>
		<th>title</th>
		<th>Genre</th>
		<th>duration</th>
		<th>action</th>
	</tr>
	{%for list in list%}
		<tr>
			<td>{{list.id}}</td>
			{# <td>{{list.title|upper}}</td> #}
			<td>{{ list.title|slice(1,2)}}</td>


			<td>{{list.genre}}</td>
			<td>{{list.duration}}</td>
			<td>
				<a href="{{ path('Add_Show') }}">Add Show</a>

			</td>
			<td>
				<a href="{{ path('th_update',{ 'id': list.id}) }}">update</a>
<a href="{{ path('app_delete', { 'id': list.id }) }}">Supprimer</a>



			</td>


		</tr>
		{%endfor%}
	</table>

templates/theatre/update.html.twig
{{form(form)}}